version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_TYPE=postgres 
      - POSTGRES_URI=postgres://postgres:postgres@postgres:5432/targeting_engine?sslmode=disable
      - DB_NAME=targeting_engine
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=targeting_engine
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    restart: unless-stopped

volumes:
  postgres_data: 